# Generated by Django 3.2 on 2022-11-19 21:37

from django.db import migrations, models
import django_zappa_event_schedular.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=255)),
                ('args', models.TextField(default='[]', validators=[django_zappa_event_schedular.validators.validate_args])),
                ('kwargs', models.TextField(default='{}', validators=[django_zappa_event_schedular.validators.validate_kwargs])),
                ('rate_value', models.IntegerField(default=1)),
                ('rate_unit', models.CharField(choices=[('minute', 'Minute'), ('minutes', 'Minutes'), ('hour', 'Hour'), ('hours', 'Hours'), ('day', 'Day'), ('days', 'Days')], default='hour', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
